# Generated by Django 5.2.4 on 2025-07-24 08:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVillaPirritx', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['-urgente', '-created_at'], 'verbose_name': 'Animal', 'verbose_name_plural': 'Animales'},
        ),
        migrations.AddField(
            model_name='animal',
            name='chip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción del carácter y personalidad'),
        ),
        migrations.AddField(
            model_name='animal',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('adoptado', 'Adoptado'), ('en_tratamiento', 'En Tratamiento')], default='disponible', max_length=20),
        ),
        migrations.AddField(
            model_name='animal',
            name='esterilizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animal',
            name='fecha_adopcion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='fecha_ingreso',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='foto_principal',
            field=models.ImageField(blank=True, null=True, upload_to='animales/'),
        ),
        migrations.AddField(
            model_name='animal',
            name='sexo',
            field=models.CharField(blank=True, choices=[('macho', 'Macho'), ('hembra', 'Hembra')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='tamaño',
            field=models.CharField(choices=[('pequeño', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande')], default='mediano', max_length=20),
        ),
        migrations.AddField(
            model_name='animal',
            name='tipo_animal',
            field=models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('otro', 'Otro')], default='perro', max_length=20),
        ),
        migrations.AddField(
            model_name='animal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='urgente',
            field=models.BooleanField(default=False, help_text='Marcar si necesita adopción urgente'),
        ),
        migrations.AddField(
            model_name='animal',
            name='vacunado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animal',
            name='visible',
            field=models.BooleanField(default=True, help_text='Mostrar en la web'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='edad',
            field=models.PositiveIntegerField(help_text='Edad en años'),
        ),
        migrations.CreateModel(
            name='FotoAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='animales/galeria/')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='gestionVillaPirritx.animal')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
